version: '3.1'
services:
  db:
    image: mysql
    container_name: mysql2
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - '53000:3306'
    volumes:
      - parkingcontrol_data:/var/lib/mysql
volumes:
  parkingcontrol_data: